# $schema: https://json.schemastore.org/github-workflow.json

name: Check - Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  build:
    name: Build
    uses: rbrownwsws/apko-workflows/.github/workflows/build.yaml@b353a605c0d093ebbdcee6f1bb6da41503ad1828 # v1.0.2
    permissions:
      contents: read  # to read the source needed to build the image
    with:
      apko-config-file: 'kubectl-1.36.yaml'
      apko-lock-file: 'kubectl-1.36.lock.json'
