# $schema: https://json.schemastore.org/github-workflow.json

name: Check - Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  build:
    name: Build
    uses: rbrownwsws/apko-workflows/.github/workflows/build.yaml@3a7160d23a05da70d9171cc5d1872065780e0ece # v1.0.5
    permissions:
      contents: read  # to read the source needed to build the image
    with:
      apko-config-file: 'kubectl-1.36.yaml'
      apko-lock-file: 'kubectl-1.36.lock.json'
