# $schema: https://json.schemastore.org/github-workflow.json

name: Check - Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  build:
    name: Build
    uses: rbrownwsws/apko-workflows/.github/workflows/build.yaml@d85532ca2145ce22b31b9be5b64d97b6913edc81 # master
    permissions:
      contents: read  # to read the source needed to build the image
    with:
      apko-config-file: 'kubectl-1.36.yaml'
      apko-lock-file: 'kubectl-1.36.lock.json'
