# $schema: https://json.schemastore.org/github-workflow.json

name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - kubectl-1.36.yaml
      - kubectl-1.36.lock.json

permissions: {}

jobs:
  build:
    name: Release
    uses: rbrownwsws/apko-workflows/.github/workflows/release.yaml@3568c0df8f79db3b0f8cfbeac408f26a6f5c3a6c # master
    permissions:
      contents: read            # to read the source needed to build the image
      id-token: write           # to get ID needed to sign attestations
      packages: write           # to store attestations
      attestations: write       # to store attestations
      artifact-metadata: write  # to store attestations
    with:
      apko-config-file: 'kubectl-1.36.yaml'
      apko-lock-file: 'kubectl-1.36.lock.json'
      image-tag: 'kubectl-1.36'
