# $schema: https://json.schemastore.org/github-workflow.json

name: Update lock files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  update:
    name: Update lock files
    uses: rbrownwsws/apko-workflows/.github/workflows/update-lock-file.yaml@cf8ff9c3d2ded901f2b6d25e1ef7ad5593730533 # master
    permissions:
      contents: write  # to read/write the lock file
    with:
      apko-config-file: 'kubectl-1.36.yaml'
      apko-lock-file: 'kubectl-1.36.lock.json'
      updater-app-client-id: ${{ vars.APP_CLIENT_ID }}
    secrets:
      updater-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
